# Generated by Django 4.0.2 on 2023-03-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='stimulus',
            options={'verbose_name_plural': 'Stimuli'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
