# Generated by Django 4.2.3 on 2023-08-02 09:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together={('name', 'created_by')},
        ),
        migrations.AlterUniqueTogether(
            name='stimulus',
            unique_together={('name', 'created_by')},
        ),
    ]
