# Generated by Django 4.2.3 on 2023-08-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorgroupqrcode',
            name='qr_code',
            field=models.ImageField(blank=True, default=None, editable=False, null=True, upload_to='qr_codes'),
        ),
    ]
