# Generated by Django 4.0.10 on 2023-05-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0002_age_education_frontendurl_gender_nationality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontendurl',
            name='url',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
