# Generated by Django 4.2.3 on 2023-08-08 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0003_alter_visitorgroupqrcode_qr_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='school',
        ),
    ]
