# Generated by Django 4.0.10 on 2023-05-23 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0003_alter_frontendurl_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='date',
            new_name='date_from',
        ),
        migrations.RemoveField(
            model_name='visitorgroup',
            name='gender',
        ),
        migrations.AddField(
            model_name='activity',
            name='date_to',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='frontendurl',
            name='activity_step',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='activity_data.activitystep'),
        ),
    ]
