# Generated by Django 4.0.2 on 2023-03-30 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0004_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='description_local',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='activity',
            name='language_local',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='activity_data.language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='name_local',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='activitystep',
            name='description_local',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='activitystep',
            name='language_local',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='activity_data.language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitystep',
            name='name_local',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='age',
            name='description_local',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='age',
            name='language_local',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='activity_data.language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='age',
            name='name_local',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='context',
            name='description_local',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='context',
            name='language_local',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='activity_data.language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='context',
            name='name_local',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='description_local',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='language_local',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='activity_data.language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='name_local',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='language',
            name='description_local',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='language',
            name='language_local',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='activity_data.language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='name_local',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='nature',
            name='description_local',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='nature',
            name='language_local',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='activity_data.language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nature',
            name='name_local',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='description_local',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='language_local',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='activity_data.language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name_local',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='stimulus',
            name='description_local',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='stimulus',
            name='language_local',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='activity_data.language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stimulus',
            name='name_local',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='activity',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_language', to='activity_data.language'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='activitystep',
            name='description',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='activitystep',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='age',
            name='description',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='age',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='context',
            name='description',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='context',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='language',
            name='description',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='nature',
            name='description',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='nature',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='stimulus',
            name='description',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='stimulus',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
