# Generated by Django 4.0.10 on 2023-05-24 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity_data', '0004_rename_date_activity_date_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorGroupQRCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('name_local', models.CharField(blank=True, default=None, max_length=255)),
                ('description_local', models.CharField(blank=True, default=None, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('url', models.CharField(default=None, max_length=255)),
                ('activity', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='activity_data.activity')),
                ('activity_step', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='activity_data.activitystep')),
                ('created_by', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='activity_data.event')),
                ('language_local', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='activity_data.language')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='visitorgroup',
            name='frontend_url',
        ),
        migrations.DeleteModel(
            name='FrontendURL',
        ),
        migrations.AddField(
            model_name='visitorgroupqrcodes',
            name='visitor_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='activity_data.visitorgroup'),
        ),
    ]
