# Generated by Django 4.2.3 on 2023-08-08 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0004_remove_visitor_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='visitor_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='activity_data.visitorgroup'),
        ),
    ]
