# Generated by Django 4.0.2 on 2023-03-30 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0005_activity_description_local_activity_language_local_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('description', models.CharField(default=None, max_length=255)),
                ('name_local', models.CharField(default=None, max_length=255)),
                ('description_local', models.CharField(default=None, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('language_local', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='activity_data.language')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('description', models.CharField(default=None, max_length=255)),
                ('name_local', models.CharField(default=None, max_length=255)),
                ('description_local', models.CharField(default=None, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(default=None, max_length=255)),
                ('language_local', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='activity_data.language')),
                ('subtype', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subtype', to='activity_data.organisationtype')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='activity_data.organisationtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('description', models.CharField(default=None, max_length=255)),
                ('name_local', models.CharField(default=None, max_length=255)),
                ('description_local', models.CharField(default=None, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('language_local', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='activity_data.language')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
