# Generated by Django 4.2.3 on 2023-08-09 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0005_alter_visitor_visitor_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='is_visitor',
        ),
    ]
