# Generated by Django 4.0.2 on 2023-03-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0006_organisationtype_organisation_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='description_local',
        ),
        migrations.RemoveField(
            model_name='language',
            name='language_local',
        ),
        migrations.RemoveField(
            model_name='language',
            name='name_local',
        ),
        migrations.AddField(
            model_name='language',
            name='code',
            field=models.CharField(default=None, max_length=6),
        ),
    ]
