# Generated by Django 4.0.10 on 2023-05-24 08:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity_data', '0006_remove_visitorgroup_qr_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VisitorGroupQRCodes',
            new_name='VisitorGroupQRCode',
        ),
    ]
