# Generated by Django 4.2.3 on 2023-08-09 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity_data', '0006_remove_organisation_is_visitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(default=None, max_length=255)),
                ('name_md5', models.CharField(blank=True, default=None, editable=False, max_length=64, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('name_local', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('description_local', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('language_local', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_data.language')),
                ('object', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ps_object', to='activity_data.concept')),
                ('predicate', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ps_predicate', to='activity_data.predicate')),
                ('subject', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ps_subject', to='activity_data.product')),
            ],
            options={
                'abstract': False,
                'unique_together': {('name', 'created_by')},
            },
        ),
    ]
