# Generated by Django 4.2.3 on 2023-08-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0007_productstatement'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='qr_codes'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_uriref',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
