# Generated by Django 4.0.2 on 2023-03-30 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0007_remove_language_description_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description_local',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='activity',
            name='language_local',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='activity_data.language'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name_local',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='activitystep',
            name='description_local',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='activitystep',
            name='language_local',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='activity_data.language'),
        ),
        migrations.AlterField(
            model_name='activitystep',
            name='name_local',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='age',
            name='description_local',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='age',
            name='language_local',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='activity_data.language'),
        ),
        migrations.AlterField(
            model_name='age',
            name='name_local',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='class',
            name='description_local',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='class',
            name='language_local',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='activity_data.language'),
        ),
        migrations.AlterField(
            model_name='class',
            name='name_local',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='context',
            name='description_local',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='context',
            name='language_local',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='activity_data.language'),
        ),
        migrations.AlterField(
            model_name='context',
            name='name_local',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_local',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='language_local',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='activity_data.language'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name_local',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='nature',
            name='description_local',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='nature',
            name='language_local',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='activity_data.language'),
        ),
        migrations.AlterField(
            model_name='nature',
            name='name_local',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='description_local',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='language_local',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='activity_data.language'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='name_local',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='organisationtype',
            name='description_local',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='organisationtype',
            name='language_local',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='activity_data.language'),
        ),
        migrations.AlterField(
            model_name='organisationtype',
            name='name_local',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_local',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='language_local',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='activity_data.language'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_local',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='stimulus',
            name='description_local',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='stimulus',
            name='language_local',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='activity_data.language'),
        ),
        migrations.AlterField(
            model_name='stimulus',
            name='name_local',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
    ]
