# Generated by Django 4.2.3 on 2023-08-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0008_product_image_product_image_uriref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='product_images'),
        ),
    ]
