# Generated by Django 4.0.10 on 2023-05-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0009_alter_activity_date_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorgroupqrcode',
            name='qr_code',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='qr_codes'),
        ),
    ]
