# Generated by Django 4.0.10 on 2023-05-25 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0010_visitorgroupqrcode_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visitor_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='activity_data.visitorgroup'),
        ),
    ]
