# Generated by Django 4.2.3 on 2023-08-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0010_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_resource_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
