# Generated by Django 4.2.3 on 2023-08-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0011_product_image_resource_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stimulus',
            name='stimulus_type',
            field=models.CharField(choices=[('Document', 'Document'), ('Segment', 'Segment'), ('Image', 'Image'), ('Audio', 'Audio'), ('Video', 'Video'), ('Tool', 'Tool'), ('Questionnaire', 'Questionnaire')], max_length=16),
        ),
    ]
