# Generated by Django 4.0.10 on 2023-05-25 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0011_product_visitor_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='visitor_group',
        ),
        migrations.AddField(
            model_name='product',
            name='data',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='visitor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='activity_data.visitor'),
        ),
    ]
