# Generated by Django 4.0.10 on 2023-05-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0012_remove_product_visitor_group_product_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
    ]
