# Generated by Django 4.0.10 on 2023-05-25 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0013_alter_visitor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='url',
        ),
        migrations.AddField(
            model_name='visitor',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='description_local',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='visitor',
            name='language_local',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='activity_data.language'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='name_local',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='motherLanguage',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mother_language', to='activity_data.language'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
