# Generated by Django 4.2.3 on 2023-08-12 23:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity_data', '0014_alter_concept_name_alter_concept_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('name', 'created_by')},
        ),
    ]
