# Generated by Django 4.0.2 on 2023-03-30 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0014_group_description_group_description_local_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='age',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='activity_data.age'),
        ),
    ]
