# Generated by Django 4.0.10 on 2023-05-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0014_remove_organisation_url_visitor_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description_local',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activitystep',
            name='name_local',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='age',
            name='description_local',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),

        migrations.AlterField(
            model_name='class',
            name='name_local',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),

        migrations.AlterField(
            model_name='context',
            name='name_local',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='description_local',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_local',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gender',
            name='name_local',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='description_local',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nature',
            name='name_local',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='description_local',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organisationtype',
            name='name_local',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_local',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stimulus',
            name='name_local',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='description_local',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visitorgroup',
            name='name_local',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visitorgroupqrcode',
            name='description_local',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
