# Generated by Django 4.0.2 on 2023-04-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0015_group_age'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='UserGroup',
        ),
        migrations.AddField(
            model_name='organisationtype',
            name='isvisitor',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
