# Generated by Django 4.2.3 on 2023-08-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0015_alter_class_options_alter_class_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='stimulus',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='stimulus_images/'),
        ),
        migrations.AddField(
            model_name='stimulus',
            name='image_resource_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='stimulus',
            name='image_uriref',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='stimulus',
            name='text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
