# Generated by Django 4.0.2 on 2023-04-09 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0016_rename_group_usergroup_organisationtype_isvisitor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisationtype',
            old_name='isvisitor',
            new_name='is_visitor',
        ),
    ]
