# Generated by Django 4.0.10 on 2023-05-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0016_remove_product_date_visitor_date_of_visit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='school',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='date_of_visit',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
