# Generated by Django 4.2.3 on 2023-08-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0017_stimulus_wordpress_post_alter_stimulus_stimulus_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stimulus',
            name='wordpress_post',
        ),
        migrations.AddField(
            model_name='stimulus',
            name='questionnaire',
            field=models.CharField(blank=True, choices=[('', '---------')], max_length=512, null=True),
        ),
    ]
