# Generated by Django 4.0.2 on 2023-04-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0017_rename_isvisitor_organisationtype_is_visitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationtype',
            name='is_visitor',
        ),
        migrations.AddField(
            model_name='organisation',
            name='is_visitor',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
