# Generated by Django 4.2.3 on 2023-08-21 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0018_remove_stimulus_wordpress_post_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['name'], 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='activitystep',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='age',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['name'], 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='concept',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='concepttype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='context',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='digitisationapplication',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='gender',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='nationality',
            options={'ordering': ['name'], 'verbose_name_plural': 'Nationalities'},
        ),
        migrations.AlterModelOptions(
            name='nature',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='organisationtype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='predicate',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='productstatement',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='statement',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='stimulus',
            options={'ordering': ['name'], 'verbose_name_plural': 'Stimuli'},
        ),
        migrations.AlterModelOptions(
            name='visitor',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='visitorgroup',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='visitorgroupqrcode',
            options={'ordering': ['name']},
        ),
    ]
