# Generated by Django 4.0.2 on 2023-04-09 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0018_remove_organisationtype_is_visitor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='useid',
            new_name='userid',
        ),
    ]
