# Generated by Django 4.2.1 on 2023-06-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0018_activity_uuid_activitystep_uuid_age_uuid_class_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='name_md5',
            field=models.CharField(blank=True, default=None, editable=False, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='activitystep',
            name='name_md5',
            field=models.CharField(blank=True, default=None, editable=False, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='age',
            name='name_md5',
            field=models.CharField(blank=True, default=None, editable=False, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='name_md5',
            field=models.CharField(blank=True, default=None, editable=False, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='context',
            name='name_md5',
            field=models.CharField(blank=True, default=None, editable=False, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='name_md5',
            field=models.CharField(blank=True, default=None, editable=False, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='name_md5',
            field=models.CharField(blank=True, default=None, editable=False, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='gender',
            name='name_md5',
            field=models.CharField(blank=True, default=None, editable=False, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='nationality',
            name='name_md5',
            field=models.CharField(blank=True, default=None, editable=False, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='nature',
            name='name_md5',
            field=models.CharField(blank=True, default=None, editable=False, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='name_md5',
            field=models.CharField(blank=True, default=None, editable=False, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='organisationtype',
            name='name_md5',
            field=models.CharField(blank=True, default=None, editable=False, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_md5',
            field=models.CharField(blank=True, default=None, editable=False, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='stimulus',
            name='name_md5',
            field=models.CharField(blank=True, default=None, editable=False, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='name_md5',
            field=models.CharField(blank=True, default=None, editable=False, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='visitorgroup',
            name='name_md5',
            field=models.CharField(blank=True, default=None, editable=False, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='visitorgroupqrcode',
            name='name_md5',
            field=models.CharField(blank=True, default=None, editable=False, max_length=16, null=True),
        ),
    ]
