# Generated by Django 4.2.1 on 2023-06-01 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0019_activity_name_md5_activitystep_name_md5_age_name_md5_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stimulus',
            name='activity_step',
        ),
        migrations.AddField(
            model_name='activitystep',
            name='stimulus',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='activity_data.stimulus'),
        ),
    ]
