# Generated by Django 4.2.1 on 2023-06-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0020_remove_stimulus_activity_step_activitystep_stimulus'),
    ]

    operations = [
        migrations.AddField(
            model_name='stimulus',
            name='uriref',
            field=models.CharField(default=None, max_length=512),
        ),
    ]
