# Generated by Django 4.0.2 on 2023-04-09 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0020_visitor_remove_usertype_language_local_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='event',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='step',
        ),
        migrations.RemoveField(
            model_name='activitystep',
            name='product',
        ),
        migrations.RemoveField(
            model_name='activitystep',
            name='stimulus',
        ),
        migrations.AddField(
            model_name='activitystep',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='activity_data.activity'),
        ),
        migrations.AddField(
            model_name='event',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='activity_data.activity'),
        ),
        migrations.AddField(
            model_name='product',
            name='step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='activity_data.activitystep'),
        ),
        migrations.AddField(
            model_name='stimulus',
            name='step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='activity_data.activitystep'),
        ),
    ]
