# Generated by Django 4.2.1 on 2023-06-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0021_stimulus_uriref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stimulus',
            name='uriref',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
