# Generated by Django 4.0.2 on 2023-04-09 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0021_remove_activity_event_remove_activity_step_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='activity',
        ),
        migrations.AddField(
            model_name='activity',
            name='Event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='activity_data.event'),
        ),
    ]
