# Generated by Django 4.2.3 on 2023-08-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0021_stimulus_document_stimulus_document_resource_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stimulus',
            name='questionnaire_wp_form',
            field=models.CharField(blank=True, choices=[('', '---------')], max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='stimulus',
            name='questionnaire_wp_post',
            field=models.CharField(blank=True, choices=[('', '---------')], max_length=512, null=True),
        ),
    ]
