# Generated by Django 4.2.3 on 2023-08-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0022_stimulus_questionnaire_wp_form_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stimulus',
            name='questionnaire_wp_form',
        ),
        migrations.AddField(
            model_name='stimulus',
            name='questionnaire_wp_form_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
