# Generated by Django 4.2.1 on 2023-06-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0022_alter_stimulus_uriref'),
    ]

    operations = [
        migrations.AddField(
            model_name='stimulus',
            name='stimulus_type',
            field=models.CharField(choices=[('Document', 'Document'), ('Segment', 'Segment'), ('Image', 'Image'), ('Video', 'Video'), ('Tool', 'Tool')], default=None, max_length=16),
        ),
    ]
