# Generated by Django 4.2.1 on 2023-06-01 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0023_stimulus_stimulus_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='motherLanguage',
            new_name='mother_language',
        ),
        migrations.RenameField(
            model_name='visitorgroup',
            old_name='motherLanguage',
            new_name='mother_language',
        ),
    ]
