# Generated by Django 4.2.1 on 2023-06-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0024_rename_motherlanguage_visitor_mother_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('MindMap', 'MindMap'), ('Other', 'Other')], default=None, max_length=16),
        ),
    ]
