# Generated by Django 4.2.3 on 2023-08-24 12:40

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0024_alter_stimulus_questionnaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, default='-23.727539,-37.983810', max_length=63, null=True),
        ),
    ]
