# Generated by Django 4.0.2 on 2023-04-09 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0024_alter_activitystep_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='activity_data.activitystep'),
        ),
        migrations.AlterField(
            model_name='stimulus',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='activity_data.activitystep'),
        ),
    ]
