# Generated by Django 4.2.3 on 2023-08-25 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity_data', '0025_event_city_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, default='37.983810,23.727539', max_length=63, null=True),
        ),
        migrations.CreateModel(
            name='QuestionnaireEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(default=None, max_length=255)),
                ('name_md5', models.CharField(blank=True, default=None, editable=False, max_length=64, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('name_local', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('description_local', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('wpforms_entry_id', models.IntegerField(blank=True, default=None, null=True)),
                ('wpforms_form_id', models.IntegerField(blank=True, default=None, null=True)),
                ('wpforms_status', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('language_local', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_data.language')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='activity_data.product')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(default=None, max_length=255)),
                ('name_md5', models.CharField(blank=True, default=None, editable=False, max_length=64, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('name_local', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('description_local', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('answer_type', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('answer_value', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('answer_value_raw', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('language_local', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_data.language')),
                ('questionnaire_entry', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='activity_data.questionnaireentry')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
