# Generated by Django 4.0.2 on 2023-04-09 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0025_alter_product_step_alter_stimulus_step'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='step',
            new_name='activity_step',
        ),
        migrations.RenameField(
            model_name='stimulus',
            old_name='step',
            new_name='activity_step',
        ),
    ]
