# Generated by Django 4.2.3 on 2023-08-25 14:36

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0026_alter_event_location_questionnaireentry_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionnaireentry',
            options={'ordering': ['name'], 'verbose_name_plural': 'Questionnaire Entries'},
        ),
        migrations.AddField(
            model_name='visitor',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, default='37.983810,23.727539', max_length=63, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='visitor',
            unique_together={('activity', 'visitor_group', 'name')},
        ),
    ]
