# Generated by Django 4.2.1 on 2023-06-07 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity_data', '0026_alter_visitor_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='gender',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='activity_data.gender'),
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(default=None, max_length=255)),
                ('name_md5', models.CharField(blank=True, default=None, editable=False, max_length=16, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('name_local', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('description_local', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('relation', models.CharField(choices=[('Consequence', 'Consequence'), ('Equivalent', 'Equivalent'), ('Opposite', 'Opposite')], default=None, max_length=16)),
                ('context_1', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='context1', to='activity_data.context')),
                ('context_2', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='context2', to='activity_data.context')),
                ('created_by', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('language_local', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='activity_data.language')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='activity_data.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
