# Generated by Django 4.2.1 on 2023-06-07 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0027_alter_visitor_gender_statement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statement',
            name='context_1',
        ),
        migrations.RemoveField(
            model_name='statement',
            name='context_2',
        ),
        migrations.AddField(
            model_name='statement',
            name='context1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='context1', to='activity_data.context'),
        ),
        migrations.AddField(
            model_name='statement',
            name='context2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='context2', to='activity_data.context'),
        ),
    ]
