# Generated by Django 4.2.1 on 2023-06-07 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0028_remove_statement_context_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statement',
            old_name='context1',
            new_name='context_1',
        ),
        migrations.RenameField(
            model_name='statement',
            old_name='context2',
            new_name='context_2',
        ),
    ]
