# Generated by Django 4.0.2 on 2023-04-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0028_alter_event_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='is_visitor',
            field=models.BooleanField(),
        ),
    ]
