# Generated by Django 4.0.2 on 2023-04-09 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0029_alter_organisation_is_visitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='is_visitor',
        ),
    ]
