# Generated by Django 4.2.3 on 2023-09-08 16:59

import activity_data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0029_questionnairequestion_questionnaireanswer_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stimulus',
            name='document',
            field=models.FileField(blank=True, default=None, null=True, upload_to=activity_data.models.Stimulus_remove_spaces_from_filename),
        ),
        migrations.AlterField(
            model_name='stimulus',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=activity_data.models.Stimulus_remove_spaces_from_image_filename),
        ),
    ]
