# Generated by Django 4.0.2 on 2023-04-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0030_remove_organisation_is_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='is_visitor',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
    ]
