# Generated by Django 4.2.5 on 2023-09-08 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0031_alter_product_document_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionnaireentry',
            options={'ordering': ['name'], 'verbose_name_plural': 'Questionnaire entries'},
        ),
    ]
