# Generated by Django 4.2.1 on 2023-06-18 08:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity_data', '0031_activity_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nationality',
            options={'verbose_name_plural': 'Nationalities'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='name_md5',
            field=models.CharField(blank=True, default=None, editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='activitystep',
            name='name_md5',
            field=models.CharField(blank=True, default=None, editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='age',
            name='name',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='age',
            name='name_md5',
            field=models.CharField(blank=True, default=None, editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='name_md5',
            field=models.CharField(blank=True, default=None, editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='concept',
            name='name',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='concept',
            name='name_md5',
            field=models.CharField(blank=True, default=None, editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='context',
            name='name_md5',
            field=models.CharField(blank=True, default=None, editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='name_md5',
            field=models.CharField(blank=True, default=None, editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name_md5',
            field=models.CharField(blank=True, default=None, editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='gender',
            name='name',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='gender',
            name='name_md5',
            field=models.CharField(blank=True, default=None, editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(default=None, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='name',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='name_md5',
            field=models.CharField(blank=True, default=None, editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='nature',
            name='name',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='nature',
            name='name_md5',
            field=models.CharField(blank=True, default=None, editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='name_md5',
            field=models.CharField(blank=True, default=None, editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='organisationtype',
            name='name',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='organisationtype',
            name='name_md5',
            field=models.CharField(blank=True, default=None, editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='predicate',
            name='name',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='predicate',
            name='name_md5',
            field=models.CharField(blank=True, default=None, editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_md5',
            field=models.CharField(blank=True, default=None, editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='name_md5',
            field=models.CharField(blank=True, default=None, editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='statement',
            name='name_md5',
            field=models.CharField(blank=True, default=None, editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='stimulus',
            name='name_md5',
            field=models.CharField(blank=True, default=None, editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='name_md5',
            field=models.CharField(blank=True, default=None, editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='visitorgroup',
            name='name_md5',
            field=models.CharField(blank=True, default=None, editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='visitorgroupqrcode',
            name='name_md5',
            field=models.CharField(blank=True, default=None, editable=False, max_length=64, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='activitystep',
            unique_together={('name', 'created_by')},
        ),
        migrations.AlterUniqueTogether(
            name='context',
            unique_together={('name', 'created_by')},
        ),
        migrations.AlterUniqueTogether(
            name='education',
            unique_together={('name', 'created_by')},
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('name', 'created_by')},
        ),
        migrations.AlterUniqueTogether(
            name='organisation',
            unique_together={('name', 'created_by')},
        ),
        migrations.AlterUniqueTogether(
            name='visitorgroup',
            unique_together={('name', 'created_by')},
        ),
    ]
