# Generated by Django 4.2.5 on 2023-10-04 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity_data', '0034_product_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(default=None, max_length=255)),
                ('name_md5', models.CharField(blank=True, default=None, editable=False, max_length=64, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('name_local', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('description_local', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('span_type', models.CharField(choices=[('text', 'Text')], max_length=32)),
                ('start', models.IntegerField(blank=True, default=None, null=True)),
                ('end', models.IntegerField(blank=True, default=None, null=True)),
                ('x', models.IntegerField(blank=True, default=None, null=True)),
                ('y', models.IntegerField(blank=True, default=None, null=True)),
                ('width', models.IntegerField(blank=True, default=None, null=True)),
                ('height', models.IntegerField(blank=True, default=None, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('language_local', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_data.language')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='activity_data.product')),
                ('value', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='activity_data.concept')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'unique_together': {('name', 'created_by')},
            },
        ),
    ]
