# Generated by Django 4.2.2 on 2023-06-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0035_alter_activity_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
    ]
