# Generated by Django 4.2.5 on 2023-10-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0035_productannotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stimulus',
            name='stimulus_type',
            field=models.CharField(choices=[('Document', 'Document'), ('Segment', 'Segment'), ('Image', 'Image'), ('Audio', 'Audio'), ('Video', 'Video'), ('Game', 'Game'), ('Presentation', 'Presentation'), ('Tool', 'Tool'), ('Questionnaire', 'Questionnaire'), ('Live Performance', 'Live Performance'), ('Senses', 'Senses')], max_length=32),
        ),
    ]
