# Generated by Django 4.2.2 on 2023-06-18 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0036_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='context',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity_data.context'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='education',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_data.education'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity_data.event'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_language', to='activity_data.language'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='language_local',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_data.language'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='nature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity_data.nature'),
        ),
        migrations.AlterField(
            model_name='activitystep',
            name='activity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='activity_data.activity'),
        ),
        migrations.AlterField(
            model_name='activitystep',
            name='language_local',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_data.language'),
        ),
        migrations.AlterField(
            model_name='activitystep',
            name='stimulus',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='activity_data.stimulus'),
        ),
        migrations.AlterField(
            model_name='age',
            name='language_local',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_data.language'),
        ),
        migrations.AlterField(
            model_name='class',
            name='language_local',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_data.language'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='language_local',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_data.language'),
        ),
        migrations.AlterField(
            model_name='context',
            name='language_local',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_data.language'),
        ),
        migrations.AlterField(
            model_name='education',
            name='language_local',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_data.language'),
        ),
        migrations.AlterField(
            model_name='event',
            name='host_organisation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='activity_data.organisation'),
        ),
        migrations.AlterField(
            model_name='event',
            name='language_local',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_data.language'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='language_local',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_data.language'),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='language_local',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_data.language'),
        ),
        migrations.AlterField(
            model_name='nature',
            name='language_local',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_data.language'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='language_local',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_data.language'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtype', to='activity_data.organisationtype'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity_data.organisationtype'),
        ),
        migrations.AlterField(
            model_name='organisationtype',
            name='language_local',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_data.language'),
        ),
        migrations.AlterField(
            model_name='predicate',
            name='language_local',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_data.language'),
        ),
        migrations.AlterField(
            model_name='product',
            name='activity_step',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='activity_data.activitystep'),
        ),
        migrations.AlterField(
            model_name='product',
            name='language_local',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_data.language'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='activity_data.producttype'),
        ),
        migrations.AlterField(
            model_name='product',
            name='visitor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='activity_data.visitor'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='language_local',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_data.language'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='language_local',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_data.language'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='object',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='object', to='activity_data.concept'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='predicate',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='activity_data.predicate'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='activity_data.product'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='activity_data.concept'),
        ),
        migrations.AlterField(
            model_name='stimulus',
            name='language_local',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_data.language'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='activity',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_data.activity'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='age',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_data.age'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='education',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_data.education'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='gender',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_data.gender'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_data.visitorgroup'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='language_local',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_data.language'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='mother_language',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mother_language', to='activity_data.language'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='nationality',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_data.nationality'),
        ),
        migrations.AlterField(
            model_name='visitorgroup',
            name='age',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_data.age'),
        ),
        migrations.AlterField(
            model_name='visitorgroup',
            name='education',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_data.education'),
        ),
        migrations.AlterField(
            model_name='visitorgroup',
            name='event',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_data.event'),
        ),
        migrations.AlterField(
            model_name='visitorgroup',
            name='language_local',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_data.language'),
        ),
        migrations.AlterField(
            model_name='visitorgroup',
            name='mother_language',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitor_group_language', to='activity_data.language'),
        ),
        migrations.AlterField(
            model_name='visitorgroup',
            name='nationality',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_data.nationality'),
        ),
        migrations.AlterField(
            model_name='visitorgroup',
            name='visitor_organisation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_data.organisation'),
        ),
        migrations.AlterField(
            model_name='visitorgroupqrcode',
            name='activity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='activity_data.activity'),
        ),
        migrations.AlterField(
            model_name='visitorgroupqrcode',
            name='activity_step',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='activity_data.activitystep'),
        ),
        migrations.AlterField(
            model_name='visitorgroupqrcode',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='activity_data.event'),
        ),
        migrations.AlterField(
            model_name='visitorgroupqrcode',
            name='language_local',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_data.language'),
        ),
        migrations.AlterField(
            model_name='visitorgroupqrcode',
            name='visitor_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='activity_data.visitorgroup'),
        ),
    ]
