# Generated by Django 4.2.5 on 2023-10-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0036_alter_stimulus_stimulus_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='visitor_type',
            field=models.CharField(choices=[('real', 'Real'), ('group', 'Group'), ('individuals', 'Unknown Individuals')], default='real', max_length=32),
        ),
        migrations.AddField(
            model_name='visitor',
            name='visitors_number',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
