# Generated by Django 4.2.5 on 2023-10-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0037_visitor_visitor_type_visitor_visitors_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualVisitor',
            fields=[
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('activity_data.visitor',),
        ),
        migrations.AddField(
            model_name='visitor',
            name='visitors',
            field=models.ManyToManyField(blank=True, default=None, related_name='virtual_visitor', to='activity_data.visitor'),
        ),
    ]
