# Generated by Django 4.2.2 on 2023-06-18 17:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity_data', '0037_alter_activity_context_alter_activity_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'created_by')},
        ),
        migrations.AlterUniqueTogether(
            name='statement',
            unique_together={('name', 'created_by')},
        ),
    ]
