# Generated by Django 4.2.2 on 2023-06-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0038_alter_product_name_alter_product_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorgroupqrcode',
            name='fullurl',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
