# Generated by Django 4.2.5 on 2023-10-22 11:11

import activity_data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0040_alter_questionnaireanswer_answer_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='document',
            field=models.FileField(blank=True, default=None, null=True, upload_to=activity_data.models.Activity_remove_spaces_from_filename),
        ),
        migrations.AddField(
            model_name='activity',
            name='document_resource_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='document_uriref',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
