# Generated by Django 4.2.2 on 2023-06-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0040_remove_visitorgroupqrcode_fullurl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitisationapplication',
            name='url',
            field=models.URLField(max_length=255),
        ),
    ]
