# Generated by Django 4.2.2 on 2023-06-20 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0041_alter_digitisationapplication_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorgroupqrcode',
            name='url',
            field=models.URLField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_language', to='activity_data.language'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='nature',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_data.nature'),
        ),
        migrations.AlterField(
            model_name='language',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='activity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='activity_data.activity'),
        ),
        migrations.AlterField(
            model_name='visitorgroup',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='activity_data.event'),
        ),
    ]
