# Generated by Django 4.2.2 on 2023-06-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0042_visitorgroupqrcode_url_alter_activity_language_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='digitisationapplication',
            old_name='url',
            new_name='uriref',
        ),
        migrations.AlterField(
            model_name='stimulus',
            name='uriref',
            field=models.URLField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
