# Generated by Django 4.2.2 on 2023-06-20 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0043_rename_url_digitisationapplication_uriref_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitorgroupqrcode',
            old_name='url',
            new_name='uriref',
        ),
    ]
