# Generated by Django 4.2.5 on 2023-11-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0043_culturalheritageartifact'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='ch_artifact',
            field=models.ManyToManyField(blank=True, default=None, to='activity_data.culturalheritageartifact'),
        ),
        migrations.AlterField(
            model_name='stimulus',
            name='stimulus_type',
            field=models.CharField(choices=[('Document', 'Document'), ('Segment', 'Segment'), ('Image', 'Image'), ('Audio', 'Audio'), ('Video', 'Video'), ('Game', 'Game'), ('Presentation', 'Presentation'), ('Tool', 'Tool'), ('Questionnaire', 'Questionnaire'), ('Live Performance', 'Live Performance'), ('Senses', 'Senses'), ('Template', 'Template'), ('Template Mind-Map', 'Template Mind-Map')], max_length=32),
        ),
    ]
