# Generated by Django 4.2.2 on 2023-06-20 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0044_rename_url_visitorgroupqrcode_uriref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='group',
            new_name='visitor_group',
        ),
    ]
