# Generated by Django 4.2.5 on 2023-11-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0044_activity_ch_artifact_alter_stimulus_stimulus_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='ch_artifact',
            field=models.ManyToManyField(blank=True, default=None, to='activity_data.culturalheritageartifact', verbose_name='CH Artifacts'),
        ),
    ]
