# Generated by Django 4.2.5 on 2023-12-08 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0045_alter_activity_ch_artifact'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='age',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_data.age', verbose_name='Designed for Ages'),
        ),
        migrations.AddField(
            model_name='activity',
            name='europeana_urirf',
            field=models.URLField(blank=True, max_length=8000, null=True),
        ),
    ]
