# Generated by Django 4.2.5 on 2023-12-08 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0046_activity_age_activity_europeana_urirf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='europeana_urirf',
            new_name='europeana_uriref',
        ),
    ]
