# Generated by Django 5.0.1 on 2024-02-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_data', '0051_alter_activitystep_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitystep',
            name='step_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Order'),
        ),
    ]
