version: '3.9'

services:
  #db:
  #  image: postgres
  #  restart: always
  #  environment:
  #    POSTGRES_USER: tasksuser_x354
  #    POSTGRES_PASSWORD: uWb47SYz5isC07qWAEYEiu
  #  volumes:
  #    - /var/vast/platform/activities-visualisation/postgresql:/var/lib/postgresql/data:Z
  #    - ./init.sql:/docker-entrypoint-initdb.d/init.sql:Z

  #admin:    
  #  image: adminer    
  #  ports:      
  #    - "8080:8080"

  db:
    image: postgres
    volumes:
      - ../data/db:/var/lib/postgresql/data:Z
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend-admin:
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_URL=${DJANGO_DATABASE_URL}
    build:
      context: ../activities-backend/
    command: /bin/sh scripts/start_django.sh
    ports:
      - "6071:8000"
    depends_on:
      db:
        condition: service_healthy

  imss-mindmap-frontend-nextjs:
    depends_on:
      - backend-admin
    build: ../imss-mindmap/
    ports:
      - "6072:3000"
    restart: always

  values-workshop-frontend-nextjs:
    depends_on:
      - backend-admin
    build: ../values-workshop/
    ports:
      - "6073:3000"
    restart: always
    
