version: '3.9'

services:
  #db:
  #  image: postgres
  #  restart: always
  #  environment:
  #    POSTGRES_USER: tasksuser_x354
  #    POSTGRES_PASSWORD: uWb47SYz5isC07qWAEYEiu
  #  volumes:
  #    - /var/vast/platform/activities-visualisation/postgresql:/var/lib/postgresql/data:Z
  #    - ./init.sql:/docker-entrypoint-initdb.d/init.sql:Z

  #admin:    
  #  image: adminer    
  #  ports:      
  #    - "8080:8080"

  db:
    image: postgres
    volumes:
      - ../data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=tasksuser_x354
      - POSTGRES_PASSWORD=uWb47SYz5isC07qWAEYEiu

  backend-admin:
    build: ../activities-backend/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ..:/code
    ports:
      - "6071:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=tasksuser_x354
      - POSTGRES_PASSWORD=uWb47SYz5isC07qWAEYEiu
    depends_on:
      - db

  imss-mindmap-frontend-nextjs:
    depends_on:
      - backend-admin
    build: ../imss-mindmap/
    ports:
      - "6072:3000"
    restart: always

  values-workshop-frontend-nextjs:
    depends_on:
      - backend-admin
    build: ../values-workshop/
    ports:
      - "6073:3000"
    restart: always
