version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: tasksuser_x354
      POSTGRES_PASSWORD: uWb47SYz5isC07qWAEYEiu
    volumes:
      - /var/vast/platform/activities-visualisation/imss-mindmap/postgresql:/var/lib/postgresql/data:Z
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:Z

  #admin:    
  #  image: adminer    
  #  ports:      
  #    - "8080:8080"

  backend-admin:
    depends_on:
      - db
    build: ../backend/
    ports:
      - "6070:80"
    restart: always
    
  backend-httprequests:
    depends_on:
      - db
    build: ../backend-httprequests/
    ports:
      - "6073:6072"
    restart: always

  galileo-frontend-nextjs:
    depends_on:
      - backend-admin
      - backend-httprequests
    build: ../galileo/
    ports:
      - "6071:3000"
    restart: always

  values-workshop-frontend-nextjs:
    depends_on:
      - backend-admin
      - backend-httprequests
    build: ../values-workshop/
    ports:
      - "6072:3000"
    restart: always