version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: tasksuser_x354
      POSTGRES_PASSWORD: uWb47SYz5isC07qWAEYEiu
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  admin:    
    image: adminer    
    ports:      
      - "8080:8080"

  backend-admin:
    depends_on:
      - db
    build: ../backend/
    ports:
      - "6070:80"
    restart: always

  frontend-nextjs:
    depends_on:
      - backend-admin
    build: ../frontend
    ports:
      - "6071:3000"
    restart: always
    