version: '3.9'

services:
  db:
    image: mysql
    volumes:
      - /var/vast/platform/activities-visualisation/imss-mindmap/mysql:/var/lib/mysql:Z
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tGwBP2fq2XRUIIdygVXWVX
      MYSQL_DATABASE: tasks_f755
      MYSQL_USER: tasksuser_x354
      MYSQL_PASSWORD: uWb47SYz5isC07qWAEYEiu

  backend-admin:
    depends_on:
      - db
    build: ../backend/
    ports:
      - "6070:80"
    restart: always

  frontend-nextjs:
    depends_on:
      - backend-admin
    build: ../frontend
    ports:
      - "6071:3000"
    restart: always
